spring.application.name=dating_app
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_LOGIN}
spring.datasource.password=${DB_PASSWORD}
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
token.signing.key=${TOKEN_SIGNING_KEY}
# ?????????? ??? ???????? ??????
app.upload.dir=${user.home}/dating_app_uploads

# (???????????) ????????? ????????????? ??????? ????? ? ??????? ??? Spring Boot
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
